package neton.quic.proto

import neton.io.core.secureRandom
import neton.io.core.secureRandomLong
import kotlin.time.Duration

// Connection ID generators (quinn-proto `cid_generator.rs`).

/**
 * Generates connection IDs for incoming connections (cid_generator.rs:10).
 *
 * Connection IDs MUST NOT contain any information that an external observer (one that does not cooperate with the
 * issuer) could use to correlate them with other connection IDs of the same connection: they must have high entropy,
 * from encrypted data or cryptographic-grade random data.
 */
interface ConnectionIdGenerator {
    /** Generate a new CID. */
    fun generateCid(): ConnectionId

    /**
     * Quickly determine whether [cid] could have been generated by this generator. False positives are permitted,
     * but increase the cost of handling invalid packets. (quinn returns `Result<(), InvalidCid>`; a failed check is
     * routine on the receive path, so here it is a Boolean.)
     */
    fun validate(cid: ConnectionId): Boolean = true

    /** The length of a CID for connections created by this generator. */
    val cidLen: Int

    /** The lifetime of generated connection IDs: they are retired after it, if set. Assumed to be constant. */
    val cidLifetime: Duration?
}

/**
 * Generates purely random connection IDs of a specified length (cid_generator.rs:48), from a cryptographically
 * secure source (quinn uses `rand::rng()`, a CSPRNG). Random CIDs can be shorter than those of
 * [HashedConnectionIdGenerator] but cannot be usefully validated.
 */
class RandomConnectionIdGenerator(
    override val cidLen: Int = 8,
    /** Fill `dst[offset, offset + length)` with random bytes; secure by default, injectable for tests. */
    private val random: (dst: ByteArray, offset: Int, length: Int) -> Unit = { d, o, l -> secureRandom(d, o, l) },
) : ConnectionIdGenerator {

    init { require(cidLen in 0..MAX_CID_SIZE) }

    override var cidLifetime: Duration? = null
        private set

    /** Set the lifetime of CIDs created by this generator. */
    fun setLifetime(d: Duration): RandomConnectionIdGenerator { cidLifetime = d; return this }

    override fun generateCid(): ConnectionId {
        val bytes = ByteArray(cidLen)
        random(bytes, 0, cidLen)
        return ConnectionId.of(bytes)
    }
}

/**
 * Generates 8-byte connection IDs that can be efficiently validated (cid_generator.rs:104): a 3-byte random nonce
 * followed by 5 bytes of a keyed FxHash of it. The hash is not cryptographic, so it can still be spoofed, but it lets
 * the endpoint drop non-QUIC packets at very low cost. The FxHash is rustc-hash 2.x's, so IDs validate across
 * quinn and this library given the same key.
 */
class HashedConnectionIdGenerator(
    private val key: Long = secureRandomLong(),
    private val random: (dst: ByteArray, offset: Int, length: Int) -> Unit = { d, o, l -> secureRandom(d, o, l) },
) : ConnectionIdGenerator {

    override var cidLifetime: Duration? = null
        private set

    /** Set the lifetime of CIDs created by this generator. */
    fun setLifetime(d: Duration): HashedConnectionIdGenerator { cidLifetime = d; return this }

    override val cidLen: Int get() = NONCE_LEN + SIGNATURE_LEN

    override fun generateCid(): ConnectionId {
        val bytes = ByteArray(NONCE_LEN + SIGNATURE_LEN)
        random(bytes, 0, NONCE_LEN)
        val h = signature(bytes)
        for (i in 0 until SIGNATURE_LEN) bytes[NONCE_LEN + i] = (h ushr (8 * i)).toByte() // little-endian prefix
        return ConnectionId.of(bytes)
    }

    override fun validate(cid: ConnectionId): Boolean {
        if (cid.size != NONCE_LEN + SIGNATURE_LEN) return false
        val bytes = cid.toByteArray()
        val h = signature(bytes)
        var diff = 0
        for (i in 0 until SIGNATURE_LEN) diff = diff or (bytes[NONCE_LEN + i].toInt() xor (h ushr (8 * i)).toInt())
        return diff and 0xFF == 0
    }

    private fun signature(bytes: ByteArray): Long {
        val hasher = FxHasher()
        hasher.writeU64(key)
        hasher.write(bytes, 0, NONCE_LEN)
        return hasher.finish()
    }

    private companion object {
        const val NONCE_LEN = 3 // good for more than 16 million connections
        const val SIGNATURE_LEN = 8 - NONCE_LEN // 8-byte total CID length
    }
}

/** rustc-hash 2.x `FxHasher` on a 64-bit target (only what the CID generator uses). */
internal class FxHasher {
    private var hash = 0L

    private fun addToHash(i: Long) { hash = (hash + i) * K }

    fun writeU64(i: Long) = addToHash(i)

    /** `Hasher::write`: one `write_u64` of the byte-string hash. */
    fun write(bytes: ByteArray, from: Int, to: Int) = writeU64(hashBytes(bytes, from, to))

    fun finish(): Long = hash.rotateLeft(26)

    companion object {
        private const val K = -0x0eca8515d19d563bL // 0xf1357aea2e62a9c5
        private const val SEED1 = 0x243f6a8885a308d3L
        private const val SEED2 = 0x13198a2e03707344L
        private const val PREVENT_TRIVIAL_ZERO_COLLAPSE = -0x5bf6c7ddd660ce30L // 0xa4093822299f31d0

        /** Full 128-bit product folded: `lo ^ hi` (rustc-hash `multiply_mix`, 64-bit path). */
        fun multiplyMix(x: Long, y: Long): Long = (x * y) xor unsignedMultiplyHigh(x, y)

        private fun unsignedMultiplyHigh(x: Long, y: Long): Long {
            val x0 = x and 0xFFFF_FFFFL; val x1 = x ushr 32
            val y0 = y and 0xFFFF_FFFFL; val y1 = y ushr 32
            val p00 = x0 * y0
            val p01 = x0 * y1
            val p10 = x1 * y0
            val p11 = x1 * y1
            val middle = (p00 ushr 32) + (p01 and 0xFFFF_FFFFL) + (p10 and 0xFFFF_FFFFL)
            return p11 + (p01 ushr 32) + (p10 ushr 32) + (middle ushr 32)
        }

        private fun le64(b: ByteArray, at: Int): Long {
            var v = 0L
            for (i in 7 downTo 0) v = (v shl 8) or (b[at + i].toLong() and 0xFF)
            return v
        }

        private fun le32(b: ByteArray, at: Int): Long {
            var v = 0L
            for (i in 3 downTo 0) v = (v shl 8) or (b[at + i].toLong() and 0xFF)
            return v
        }

        /** rustc-hash `hash_bytes`. */
        fun hashBytes(bytes: ByteArray, from: Int, to: Int): Long {
            val len = to - from
            var s0 = SEED1
            var s1 = SEED2
            if (len <= 16) {
                if (len >= 8) {
                    s0 = s0 xor le64(bytes, from)
                    s1 = s1 xor le64(bytes, to - 8)
                } else if (len >= 4) {
                    s0 = s0 xor le32(bytes, from)
                    s1 = s1 xor le32(bytes, to - 4)
                } else if (len > 0) {
                    val lo = bytes[from].toLong() and 0xFF
                    val mid = bytes[from + len / 2].toLong() and 0xFF
                    val hi = bytes[to - 1].toLong() and 0xFF
                    s0 = s0 xor lo
                    s1 = s1 xor ((hi shl 8) or mid)
                }
            } else {
                var p = from
                val bulkEnd = to - 1
                while (bulkEnd - p >= 16) {
                    val x = le64(bytes, p)
                    val y = le64(bytes, p + 8)
                    val t = multiplyMix(s0 xor x, PREVENT_TRIVIAL_ZERO_COLLAPSE xor y)
                    s0 = s1
                    s1 = t
                    p += 16
                }
                s0 = s0 xor le64(bytes, to - 16)
                s1 = s1 xor le64(bytes, to - 8)
            }
            return multiplyMix(s0, s1) xor len.toLong()
        }
    }
}
